### ISSUE TITLE
FileSystemException by Pana 

### ISSUE THREAD

**Issue by SimonIT** [axel-op/dart_package_analyzer#17]
```json
{"level":"SHOUT","message":"Problem analyzing /github/workspace","error":"FileSystemException: Directory listing failed, path = '/github/workspace\n/' (OS Error: No such file or directory, errno = 2)","stackTrace":""}
```

Here's the config
https://github.com/ThinkSimple/flutter_simple_shopify/blob/master/.github/workflows/build.yml
with the failing run:
https://github.com/ThinkSimple/flutter_simple_shopify/runs/3363635303

It fails also with another repo with the same exception:
https://github.com/SimonIT/timetracker/blob/master/.github/workflows/build.yml
https://github.com/SimonIT/timetracker/runs/3360920067

**Comment by Rexios80** [comment]
Same here. It used to work fine and without touching the actions config it started failing.

**Comment by axel-op** [comment]
Hello,

Thanks for reporting this. However this is a regression introduced by a recent commit in the pana repository: see https://github.com/dart-lang/pana/issues/946. This has been fixed with https://github.com/dart-lang/pana/pull/945. I'm going to refresh the Docker image used by this action.
