### ISSUE TITLE
Action uses outdated version of pana

### ISSUE THREAD

**Issue by benthillerkus** [axel-op/dart_package_analyzer#19]
According to the report file, the runs the action did today used [`pana: ^0.21.8`](https://pub.dev/packages/pana/versions/0.21.8), however the newest version of pana is [`pana: ^0.21.10`](https://pub.dev/packages/pana/versions/0.21.10)

**Comment by axel-op** [comment]
Hello,

The update had been blocked on the CI for a few weeks due to some issue in the pana repository. It is fixed and this action now runs with pana `0.21.12` 😊
