### ISSUE TITLE
Doesn't appear to support Flutter 3.10

### ISSUE THREAD

**Issue by JaffaKetchup** [axel-op/dart_package_analyzer#23]
Hi there,
Unless I've missed something obvious, or maybe I just need a wait a bit, this doesn't seem to support Flutter 3.10? It appears as though it's checking with Flutter 3.7.12.
Thanks :)

![image](https://github.com/axel-op/dart-package-analyzer/assets/58115698/5126e92f-e1b0-48e9-b474-eaa3fd8a66fa)

**Comment by axel-op** [comment]
Fixed ;) Thanks for the issue, very responsive!

**Comment by JaffaKetchup** [comment]
@axel-op So are you :) Many thanks.
