### ISSUE TITLE
'json_output' is missing from action.yml

### ISSUE THREAD

**Issue by fujidaiti** [axel-op/dart_package_analyzer#24]
I found `json_output` is missing from the `action.yml`. Although this action works fine, linters for workflow files like [GitHub Actions](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions) warn that no such output exists, as shown in the following screenshot:

<img width="774" alt="スクリーンショット 2023-08-08 18 28 39" src="https://github.com/axel-op/dart-package-analyzer/assets/68946713/9a217929-2342-4670-afaa-dff1b914f940">

**Comment by axel-op** [comment]
Thank you for taking the time to fix this :)
