### ISSUE TITLE
Pana analysis suddenly failing

### ISSUE THREAD

**Issue by shamblett** [axel-op/dart_package_analyzer#6]
I'm getting strange SDK errors in my pana analysis, please see this [action log ](https://github.com/shamblett/mqtt5_client/actions/runs/144572555). from what I can see this started to happen when pana move up form 0.13.8-dev although this may not be the cause, also I'm not sure what the 'github#L1' errors mean.

**Comment by axel-op** [comment]
Hi, it's actually the error reported by the "Check scores" step...

**Comment by axel-op** [comment]
The message `Process completed with exit code 1.` is unclear but this is what happens when you call `exit` in a bash script with a non-zero code.

**Comment by shamblett** [comment]
Yes, any idea why it suddenly thinks the SDK is invalid?  I'll have a look at the exit code stuff.

**Comment by axel-op** [comment]
It's actually unrelated. The error that you have is because your scores are below the threshold that you set in the script.

```console
MAINTENANCE_SCORE=80.00
HEALTH_SCORE=100.00
if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
then
  echo "Scores are not both equal to 100"
  exit 1
fi
shell: /bin/bash -e {0}
Scores are not both equal to 100
##[error]Process completed with exit code 1.
```

Here you can see that the "maintenance score" is 80 therefore `$MAINTENANCE_SCORE < 100` is true.

**Comment by axel-op** [comment]
Well maybe it's not completely unrelated since the issues you see are probably what lowers your score.

**Comment by shamblett** [comment]
Ah yes I see , just to rule out this repo I updated another one of my Dart projects and the analysis run was OK with these versions being printed at the end :-
Versions
Pana: 0.13.10
Dart: 2.8.4
Flutter: 1.17.4

So whatever  it is seems to be specific to this repo, thanks for your help.

**Comment by axel-op** [comment]
You're welcome 😊
